### ISSUE TITLE
Include empty cells when converting xls to csv

### ISSUE THREAD

**Issue by eeeschwartz** [openlexington/Lex_to_LIVES#20]
The xls_to_csv.rb script should output ",," when an xls cell is empty. Instead it outputs nothing, shifting the CSV cells left.

Totally doable to include empty cells I image.

Side note: to get around this problem I've been manually uploading the Health Dept's XLS to [Google Drive and exporting as CSV](https://github.com/openlexington/Lex_to_LIVES/pull/19/files#diff-04c6e90faac2675aa89e2176d2eec7d8R10).

**Comment by mildmojo** [comment]
I think nil values in the array fed to `csv` get removed. Might be as simple as:

```diff
    CSV.open(output_file, "wb", csv_opts) do |csv|
-      row_structs.each { |row| csv << row.to_a }
+      row_structs.each { |row| csv << row.to_a.map { |c| c.nil? ? '' : c } }
    end

**Comment by eeeschwartz** [comment]
@mildmojo thanks so much! I'll give that a shot this weekend.
